FROM docker.io/jupyter/datascience-notebook:python-3.10

USER root
RUN apt-get update --yes &&\
		apt-get install --yes --no-install-recommends x11-apps xauth &&\
		apt-get clean && rm -rf /var/lib/apt/lists/*

USER ${NB_UID}
RUN python -m pip install --upgrade opencv-python ydata-profiling optuna plotly missingno dalex
WORKDIR /home/jovyan/work
